abstract class OrganizationMembershipDataStates {}

class OrganizationMembershipDataInitiateState extends OrganizationMembershipDataStates {}

class GetPersonalImageFromGallerySuccessfullyState extends OrganizationMembershipDataStates {}

class GetPersonalImageFromGalleryErrorState extends OrganizationMembershipDataStates {}

class GetNationalIDImageFromGallerySuccessfullyState extends OrganizationMembershipDataStates {}

class GetNationalIDImageFromGalleryErrorState extends OrganizationMembershipDataStates {}

class OrganizationMembershipDataSelectDateState extends OrganizationMembershipDataStates {}

class GetSubscriptionInfoLookupsLoadingState extends OrganizationMembershipDataStates {}

class GetSubscriptionInfoLookupsSuccessfullyState extends OrganizationMembershipDataStates {}

class GetSubscriptionInfoLookupsErrorState extends OrganizationMembershipDataStates {}
